site_name: UVMAT - Help with documentation and tutorials
site_url: https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/uvmat-doc/
docs_dir: ./src
site_dir: ./docs
site_author: Joel Sommeria / LEGI
copyright: Copyright (C) Joel Sommeria, 2008-2024, LEGI UMR 5519 / CNRS UGA Grenoble-INP / Grenoble, France (document generated on __DATE__)

nav:
#  - ../README.md
#  - README.md
#  - ../tutorial/README.md
  - README.md
  - help/README.md
  - tutorial/01-ImageDisplay.md
  - tutorial/02-ProjectionObjects.md
  - tutorial/03-GeometricCalibration.md
  - tutorial/04-ProcessingImageSeries.md
  - tutorial/05-ParticleImageVelocimetry.md
  - tutorial/06-CorrelationImageVelocimetryOptimisation.md
  - tutorial/07-AdvancedParticleImagingVelocimetry-1.md
  - tutorial/08-AdvancedParticleImagingVelocimetry-2.md
  - tutorial/09-DisplacementMeasuredByImageCorrelation.md
  - tutorial/10-ImageCorrelation.md
  - tutorial/11-CorrelationImageVelocimetryComponents.md
  - tutorial/12-ComparaisonNumSolution.md
  - help/ThinPlateShell.md

theme:
  name: material
  locale: fr
  #features:
  #  - navigation.instant
  features:
    - content.code.copy
  palette:
    primary: blue
    accent: darkblue

plugins:
  - macros
  #- search
  #- git-revision-date-localized
  #- with-pdf:
  #    cover_subtitle: (Version non finalisée compilé le __DATE__)
  #    output_path: pdf/guide-resinfo-wapt.pdf

markdown_extensions:
  #- codehilite:
  #    use_pygments: false
  - admonition:
  - pymdownx.emoji:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
