site_name: UVMAT - Help guide
site_url: https://legi.gricad-pages.univ-grenoble-alpes.fr/soft/uvmat-doc/
docs_dir: ../help
site_dir: ./docs/help
site_author: Joel Sommeria / LEGI
copyright: Copyright (C) Joel Sommeria, 2008-2024, LEGI UMR 5519 / CNRS UGA Grenoble-INP / Grenoble, France (document generated on __DATE__)

nav:
  - README.md

theme:
  name: material
  locale: fr
  #features:
  #  - navigation.instant
  features:
    - content.code.copy
  palette:
    primary: pink
    accent: red

plugins:
  - macros
  #- search
  #- git-revision-date-localized
  #- with-pdf:
  #    cover_subtitle: (Version non finalisée compilé le __DATE__)
  #    output_path: pdf/guide-resinfo-wapt.pdf

markdown_extensions:
  #- codehilite:
  #    use_pygments: false
  - admonition:
  - pymdownx.emoji:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list:
